config/routes.rb
Rails.application.routes.draw do
  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  root to: "sessions#welcome"

  get '/dashboard' => 'sessions#dashboard'
  get '/search' => 'search#search'
  get '/students' => 'sessions#welcome'
  get '/students/on_track/:slug' => 'sessions#on_track'
  get '/lessons/unit/:id' => 'lessons#unit'

  resources :lessons, only: [:index, :show, :update, :edit] do
    resources :notes, only: [ :create, :update]
  end

  resources :tracks, only: [:index, :create]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_student!

  def search
    @search_term = params[:search]
    text = '%' + params[:search] + '%'

    @lessons = []
    tags = current_student.tags.where("category like ? collate nocase", text)
    tags.each { |tag| @lessons << tag.lessons.to_a.flatten }
    @lessons = @lessons.flatten

    notes = current_student.notes.where("content like ? collate nocase", text)
    notes.each { |note| @lessons << note.lesson }

    lessons = current_student.lessons.where("title like ? collate nocase", text)
    @lessons += lessons.to_a.flatten unless lessons.empty?

    @lessons = @lessons.uniq
  end
end

app/views/search/index.html.erb
<h3>Search results for '<%= @search_term %>':</h3>

<% @lessons.each do |lesson| %>
  <div>
    <%= link_to lesson.title, lesson_path(lesson) %>
  </div>
<% end %>

app/views/search/search.html.erb
<h3>Search results for '<%= @search_term %>':</h3>

<% @lessons.each do |lesson| %>
  <div>
    <%= link_to lesson.title, lesson_path(lesson) %>
  </div>
<% end %>