config/routes.rb
Rails.application.routes.draw do
  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  root to: "sessions#welcome"

  get '/dashboard' => 'sessions#dashboard'
  get '/search' => 'search#search'
  get '/students' => 'sessions#welcome'
  get '/students/on_track/:slug' => 'sessions#on_track'
  get '/lessons/unit/:id' => 'lessons#unit'

  resources :lessons, only: [:index, :show, :update, :edit] do
    resources :notes, only: [ :create, :update]
  end

  resources :tracks, only: [:index, :create]
end

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], id: "flash_error", class:['alert', 'alert-danger']) if flash[:error] %>
<%= content_tag(:div, flash[:notice], id: "flash_notice", class:['alert', 'alert-success']) if flash[:notice] %>
<%= content_tag(:div, flash[:alert], id: "flash_alert", class:['alert', 'alert-warning']) if flash[:alert] %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if student_signed_in? %>
          <%= render 'layouts/signed-in' %>
        <% else %>
          <%= render 'layouts/not-signed-in' %>
        <% end %>
      </ul>

      <%= render 'layouts/search' if student_signed_in? %>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_not-signed-in.html.erb
<li>
  <%= link_to 'Sign Up', new_student_registration_path %>
</li>
<li>
  <%= link_to 'Sign In', new_student_session_path %>
</li>

app/views/layouts/_search.html.erb
<div class="pull-right">
  <%= form_tag('/search', method: :get, class: 'navbar-form', role: 'search') do %>
    <div class="input-group">
      <%= text_field_tag 'search', nil,class: "form-control", placeholder: "Search" %>
      <div class='input-group-btn'>
        <%= button_tag  content_tag(:i, nil, class:"fa fa-search"), class:'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_signed-in.html.erb
<li>
  <%= link_to "Hello, #{current_student.email}!", dashboard_path %>
</li>
<li>
  <%= link_to "Log Out", destroy_student_session_path, method: 'DELETE' %>
</li>
<% if current_track %>
  <li>
    <%= link_to 'Lessons', lessons_url %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learn-Co Companion</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <!--  navbar -->
    <%= render 'layouts/navigation' %>

    <!-- content -->

    <div class="container"  role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>